import { requireAuth } from "@/lib/auth/require-auth";
import { AppHeader } from "@/components/layout/app-header";
import { Container } from "@/components/layout/container";
import { listCheckins } from "@/db/repositories/weekly-checkin.repository";
import { getEmailPreference } from "@/db/repositories/email-preference.repository";
import { CheckinListView, type CheckinItem } from "@/components/checkins/checkin-list-view";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Weekly Check-Ins | Elevra",
  description: "Weekly automated executive coaching summaries dispatched to your email.",
};

export default async function CheckInsPage() {
  const user = await requireAuth({ requireOnboarding: true });

  const [rawCheckins, emailPref] = await Promise.all([
    listCheckins(user.id, 50),
    getEmailPreference(user.id),
  ]);

  const formattedCheckins: CheckinItem[] = rawCheckins.map((chk) => ({
    id: chk.id,
    provider: chk.provider,
    recipientEmail: chk.recipientEmail,
    subject: chk.subject,
    content: chk.content,
    status: chk.status,
    providerMessageId: chk.providerMessageId,
    errorMessage: chk.errorMessage,
    sentAt: chk.sentAt ? chk.sentAt.toISOString() : null,
    createdAt: chk.createdAt.toISOString(),
  }));

  const isConfigured = emailPref?.weeklyCheckinsEnabled ?? true;
  const destinationEmail = emailPref?.destinationEmail || user.email;
  const provider = emailPref?.provider || "resend";

  return (
    <div>
      <AppHeader
        title="Weekly Check-In Logs"
        description="Automated weekly digests generated by the coaching engine and dispatched to your email."
      />

      <div className="py-6 sm:py-8">
        <Container size="default">
          <CheckinListView
            checkins={formattedCheckins}
            emailConfigured={isConfigured}
            destinationEmail={destinationEmail}
            provider={provider}
          />
        </Container>
      </div>
    </div>
  );
}
