import { Mail, CheckCircle2, Clock } from "lucide-react";
import { AppHeader } from "@/components/layout/app-header";
import { Container } from "@/components/layout/container";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export default function CheckInsPage() {
  const checkins = [
    {
      id: "chk_1",
      week: "Week 32, 2026",
      date: "Aug 10, 2026",
      status: "sent",
      subject: "Weekly Confidence Briefing: Progress on Public Speaking Assertiveness",
      summary: "Synthesized 3 roleplay sessions. High focus on holding pause intervals during Q&A.",
      actionCount: 2,
    },
    {
      id: "chk_2",
      week: "Week 31, 2026",
      date: "Aug 3, 2026",
      status: "sent",
      subject: "Weekly Confidence Briefing: Salary Negotiation Readiness",
      summary: "Reframed imposter hesitation; established clear benchmark metrics for comp discussion.",
      actionCount: 2,
    },
  ];

  return (
    <div>
      <AppHeader
        title="Weekly Check-In Logs"
        description="Automated weekly coaching digests generated by Vercel Cron and dispatched via email."
      />

      <div className="py-8">
        <Container size="default" className="space-y-6">
          <Card className="bg-panel border-border">
            <CardHeader className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div>
                <CardTitle className="text-[15px]">Automated Cron Dispatch Schedule</CardTitle>
                <CardDescription className="text-[12.5px] mt-1">
                  Dispatches every Monday at 09:00 UTC with an AI-generated synthesis of your week.
                </CardDescription>
              </div>
              <Badge variant="success" className="shrink-0">
                Next: Monday 09:00 UTC
              </Badge>
            </CardHeader>
          </Card>

          <div className="space-y-4">
            <div className="text-[12.5px] font-medium uppercase tracking-wider text-text-muted">
              Dispatched Digest History
            </div>
            {checkins.map((chk) => (
              <Card key={chk.id} className="bg-panel border-border">
                <CardHeader className="pb-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Mail className="h-4 w-4 text-accent" />
                      <span className="text-[13.5px] font-medium text-text-primary">
                        {chk.subject}
                      </span>
                    </div>
                    <Badge variant="success">Sent</Badge>
                  </div>
                  <div className="text-[12px] text-text-muted mt-1">
                    {chk.week} • Delivered on {chk.date}
                  </div>
                </CardHeader>
                <CardContent className="text-[13px] text-text-secondary pt-0">
                  <p>{chk.summary}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </Container>
      </div>
    </div>
  );
}
